suh_gestion_homepage:
    path:     /
    defaults: { _controller: SUHGestionBundle:Affichage:AfficherAccueil }

suh_get_etudiant:
    path:   /get/{id}
    defaults: { _controller: SUHGestionBundle:Affichage:AfficherAccueilEtudiant }
    requirements:
        id:   "^[0-9]+$"
    
suh_get_etudiant_nomEtPrenom:
    path:   /by
    defaults: { _controller: SUHGestionBundle:Affichage:AfficherAccueilEtudiantRechercheNomOuPrenom }

#recherche avancée
suh_gestion_rechercheAvancee:
    path:     /rechercheAvancee
    defaults: { _controller: SUHGestionBundle:Affichage:AfficherRechercheAvancee }

suh_gestion_resultatAvancee:
    path: /resultatAvancee
    defaults: { _controller: SUHGestionBundle:Affichage:AfficherResultatRecherche }


#Gestion des importations et exportations excel
suh_import_export_page:
    path: /importExportExcel
    defaults: { _controller: SUHGestionBundle:Affichage:afficheImportExportPage }
    
suh_import_page:
    path: /importExcel
    defaults: { _controller: SUHGestionBundle:Excel:importExcel }
    
suh_export_page:
    path: /exportExcel
    defaults: { _controller: SUHGestionBundle:Excel:exportExcel }


#Gestion des étudiants

suh_ajout_etudiant:
    path: /ajouter/{id}
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:ajoutEtudiant }
    requirements:
        id:   "^[0-9]+$"
        
suh_modification_etudiant:
    path: /modifier/{id}
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:modificationEtudiant }
    requirements:
        id:   "^[0-9]+$"
        
suh_suppression_etudiant:
    path: /supprimer/{id}
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:suppressionEtudiant }
    requirements:
        id:   "^[0-9]+$"
     
#gestion comptes utilisateur   

suh_gestion_utilisateur_page:
    path: /gestionUtilisateurs
    defaults: { _controller: SUHGestionBundle:Affichage:afficheGestionUtilisateurPage }
    
suh_ajouter_utilisateur:
    path: /ajouterCompteUtilisateur
    defaults: { _controller: SUHGestionBundle:GestionCompteUtilisateur:ajouterCompteUtilisateur }
    
    
suh_supprimer_utilisateur:
    path: /supprimerCompteUtilisateur
    defaults: { _controller: SUHGestionBundle:GestionCompteUtilisateur:supprimerCompteUtilisateur }
        
 
#routes pour les ajouts        
suh_gestion_addEtudiant:
    path: /add
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:addInfosEtudiant }

suh_gestion_addEtudiant_Etape2:
    path: /add2
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:addInfosEtudiantEtape2 }
    
suh_gestion_addEtudiant_Etape2bis:
    path: /add2bis
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:addInfosEtudiantEtape2bis }
    
suh_gestion_addEtudiant_Etape3:
    path: /add3
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:addInfosEtudiantEtape3 }

suh_gestion_addEtudiant_Etape4:
    path: /add4
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:addInfosEtudiantEtape4 }
    
suh_gestion_addEtudiant_Etape4bis:
    path: /add4bis
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:addInfosEtudiantEtape4bis }
 
suh_gestion_addEtudiant_addInfosEtudiantIntermediaire:
    path: /addIntermediaire
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:addInfosEtudiantIntermediaire }
    
suh_gestion_addEtudiant_Etape5:
    path: /add5
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:addInfosEtudiantEtape5 }
   
suh_gestion_addEtudiant_Etape6:
    path: /add6
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:addInfosEtudiantEtape6 }
    
suh_gestion_addEtudiant_Etape6bis:
    path: /add6bis
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:addInfosEtudiantEtape6bis }
    
suh_gestion_BackStep1:
    path: /backStep1
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:BackStep1 }
    
suh_gestion_BackStep2:
    path: /backStep2
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:BackStep2 }
    
    
#route pour les modifications

suh_gestion_modifEtudiant_infos:
    path: /modifInfos
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:modifInfos }

suh_gestion_modifEtudiant_anneeScolaire:
    path: /anneeScolaire
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:modifAnneeScolaire }
    
suh_gestion_modifEtudiant_formation:
    path: /formation
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:modifFormation }
    
suh_gestion_modifEtudiant_DatesAideExamen:
    path: /DatesAideExamen
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:modifDatesAideExamen }

suh_gestion_modifEtudiant_AideExamen:
    path: /AideExamen
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:modifAideExamen }
    
suh_gestion_modifEtudiant_mdph:
    path: /mdph
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:modifmdph }
    
suh_gestion_modifEtudiant_handicap:
    path: /handicap
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:modifhandicap }
    
suh_gestion_modifEtudiant_NomHandicap:
    path: /NomHandicap
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:modifNomHandicap }
    
suh_gestion_modifEtudiant_AddNewhandicap:
    path: /AddNewHandicap
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:addNewHandicap }
    
suh_gestion_modifEtudiant_AddNewFormation:
    path: /AddNewFormation
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:addNewFormation }
    
suh_gestion_addNewFormation_Etape2:
    path: /AddNewFormation2
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:addNewFormationEtape2 }
    
suh_gestion_modifEtudiant_AddNewAideExamen:
    path: /AddNewAideExamen
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:addNewAideExamen }

suh_gestion_modifEtudiant_AddNewAideExamenEtape2:
    path: /AddNewAideExamen2
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:addNewAideExamenEtape2 }
    
#routes suppression handicap/formation/aideexamen


suh_suppression_handicap:
    path: /supprimerHandicap/{id}
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:supprimerHandicap }
    requirements:
        id:   "^[0-9]+$"
        
suh_suppression_etudiantFormation:
    path: /supprimerFormation/{id}
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:supprimerFormation }
    requirements:
        id:   "^[0-9]+$"
 
suh_suppression_datesAideExamen:
    path: /supprimerAideExamen/{id}
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:supprimerAideExamen }
    requirements:
        id:   "^[0-9]+$"