suh_gestion_homepage:
    path:     /
    defaults: { _controller: SUHGestionBundle:Affichage:AfficherAccueil }

suh_get_etudiant:
    path:   /get/{id}
    defaults: { _controller: SUHGestionBundle:Affichage:AfficherAccueilEtudiant }
    requirements:
        id:   "^[0-9]+$"
    
suh_get_etudiant_nomEtPrenom:
    path:   /by
    defaults: { _controller: SUHGestionBundle:Affichage:AfficherAccueilEtudiantRechercheNomOuPrenom }

suh_import_export_page:
    path: /importExportExcel
    defaults: { _controller: SUHGestionBundle:Affichage:afficheImportExportPage }
    
suh_import_page:
    path: /importExcel
    defaults: { _controller: SUHGestionBundle:Excel:importExcel }
    
suh_export_page:
    path: /exportExcel
    defaults: { _controller: SUHGestionBundle:Excel:exportExcel }
   
suh_ajout_etudiant:
    path: /ajouter/{id}
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:ajoutEtudiant }
    requirements:
        id:   "^[0-9]+$"
        
suh_modification_etudiant:
    path: /modifier/{id}
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:modificationEtudiant }
    requirements:
        id:   "^[0-9]+$"
        
suh_suppression_etudiant:
    path: /supprimer/{id}
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:suppressionEtudiant }
    requirements:
        id:   "^[0-9]+$"
        
        
#routes pour les ajouts        
suh_gestion_addEtudiant:
    path: /add
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:addInfosEtudiant }
 
suh_gestion_addEtudiant_Etape2:
    path: /add2
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:addInfosEtudiantEtape2 }
    
suh_gestion_addEtudiant_Etape3:
    path: /add3
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:addInfosEtudiantEtape3 }

suh_gestion_addEtudiant_Etape4:
    path: /add4
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:addInfosEtudiantEtape4 }
    
suh_gestion_addEtudiant_Etape5:
    path: /add5
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:addInfosEtudiantEtape5 }
    
suh_gestion_addEtudiant_Etape6:
    path: /add6
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:addInfosEtudiantEtape6 }
   
suh_gestion_addEtudiant_Etape7:
    path: /add7
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:addInfosEtudiantEtape7 }
    
suh_gestion_BackStep1:
    path: /backStep1
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:BackStep1 }
    
suh_gestion_BackStep2:
    path: /backStep2
    defaults: { _controller: SUHGestionBundle:GestionEtudiant:BackStep2 }