suh_gestion_homepage:
    path:     /
    defaults: { _controller: SUHGestionBundle:Affichage:AfficherAccueil }

suh_get_etudiant:
    path:   /get/{id}
    defaults: { _controller: SUHGestionBundle:Affichage:AfficherAccueilEtudiant }
    
suh_get_etudiant_nomEtPrenom:
    path:   /by
    defaults: { _controller: SUHGestionBundle:Affichage:AfficherAccueilEtudiantRechercheNomOuPrenom }

suh_import_export_page:
    path: /importExportExcel
    defaults: { _controller: SUHGestionBundle:Affichage:afficheImportExportPage }
    
suh_import_page:
    path: /importExcel
    defaults: { _controller: SUHGestionBundle:Excel:importExcel }
    
suh_export_page:
    path: /exportExcel
    defaults: { _controller: SUHGestionBundle:Excel:exportExcel }