<?php

namespace SUH\GestionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtudiantHandicapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantHandicapeRepository extends EntityRepository
{
    public function getAllIdNameSurname()
    {
        return $this->_em->createQueryBuilder()
                ->select('eh.id')
                ->from($this->_entityName,'eh')
                ->join('eh.etudiant','e')
                ->addSelect('e.nomEtudiant','e.prenomEtudiant')
                ->orderBy('e.nomEtudiant')
                ->addOrderBy('e.prenomEtudiant')
                ->getQuery()
                ->getResult();       
    }
    
    public function getInformationsStudent($id)
    {
        return $this->createQueryBuilder('eh')
                ->where('eh.id=:id')
                ->setParameter('id', $id)
                ->join('eh.etudiant','etudiant')
                ->addSelect('etudiant')
                ->join('etudiant.listEtudiantFormation','lef')
                ->addSelect('lef')
                ->join('lef.formation','formation')
                ->addSelect('formation')
                ->join('eh.mdph','mdph')
                ->addSelect('mdph')
                ->join('eh.handicap','handicap')
                ->addSelect('handicap')
                ->join('eh.datesAideExamen','dae')
                ->addSelect('dae')
                ->join('dae.aideExamen','aideExamen')
                ->addSelect('aideExamen')
                ->getQuery()
                ->getResult();
    }
    
    public function getAllStudentsInformations()
    {        
        return $this->createQueryBuilder('eh')
                ->join('eh.etudiant','etudiant')
                ->addSelect('etudiant')
                ->join('etudiant.listEtudiantFormation','lef')
                ->addSelect('lef')
                ->join('lef.formation','formation')
                ->addSelect('formation')
                ->join('eh.mdph','mdph')
                ->addSelect('mdph')
                ->join('eh.handicap','handicap')
                ->addSelect('handicap')
                ->join('eh.datesAideExamen','dae')
                ->addSelect('dae')
                ->join('dae.aideExamen','aideExamen')
                ->addSelect('aideExamen')
                ->getQuery()
                ->getResult();
    }
}
