<?php

namespace SUH\GestionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HandicapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HandicapRepository extends EntityRepository
{
    
}
