<?php

namespace Proxies\__CG__\SUH\GestionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EtudiantHandicape extends \SUH\GestionBundle\Entity\EtudiantHandicape implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'id', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'etudiant', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'qhandi', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'rqth', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'notificationSavs', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'amenagementEtude', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'tauxInvalidite', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'suivi', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'dateMaj', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'descriptifComplementaire', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'mdph', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'etudiantHandicapeHandicap', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'datesAideExamen');
        }

        return array('__isInitialized__', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'id', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'etudiant', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'qhandi', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'rqth', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'notificationSavs', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'amenagementEtude', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'tauxInvalidite', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'suivi', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'dateMaj', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'descriptifComplementaire', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'mdph', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'etudiantHandicapeHandicap', '' . "\0" . 'SUH\\GestionBundle\\Entity\\EtudiantHandicape' . "\0" . 'datesAideExamen');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EtudiantHandicape $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getDatesAideExamen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatesAideExamen', array());

        return parent::getDatesAideExamen();
    }

    /**
     * {@inheritDoc}
     */
    public function addDatesAideExamen($datesAideExamen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDatesAideExamen', array($datesAideExamen));

        return parent::addDatesAideExamen($datesAideExamen);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDatesAideExamen($datesAideExamen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDatesAideExamen', array($datesAideExamen));

        return parent::removeDatesAideExamen($datesAideExamen);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtudiantHandicapeHandicap()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtudiantHandicapeHandicap', array());

        return parent::getEtudiantHandicapeHandicap();
    }

    /**
     * {@inheritDoc}
     */
    public function addEtudiantHandicapeHandicap($etudiantHandicapeHandicap)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEtudiantHandicapeHandicap', array($etudiantHandicapeHandicap));

        return parent::addEtudiantHandicapeHandicap($etudiantHandicapeHandicap);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEtudiantHandicapeHandicap($etudiantHandicapeHandicap)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEtudiantHandicapeHandicap', array($etudiantHandicapeHandicap));

        return parent::removeEtudiantHandicapeHandicap($etudiantHandicapeHandicap);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtudiant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtudiant', array());

        return parent::getEtudiant();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtudiant($etudiant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtudiant', array($etudiant));

        return parent::setEtudiant($etudiant);
    }

    /**
     * {@inheritDoc}
     */
    public function getMdph()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMdph', array());

        return parent::getMdph();
    }

    /**
     * {@inheritDoc}
     */
    public function setMdph($mdph)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMdph', array($mdph));

        return parent::setMdph($mdph);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setQhandi($qhandi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQhandi', array($qhandi));

        return parent::setQhandi($qhandi);
    }

    /**
     * {@inheritDoc}
     */
    public function getQhandi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQhandi', array());

        return parent::getQhandi();
    }

    /**
     * {@inheritDoc}
     */
    public function setRqth($rqth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRqth', array($rqth));

        return parent::setRqth($rqth);
    }

    /**
     * {@inheritDoc}
     */
    public function getRqth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRqth', array());

        return parent::getRqth();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotificationSavs($notificationSavs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotificationSavs', array($notificationSavs));

        return parent::setNotificationSavs($notificationSavs);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotificationSavs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotificationSavs', array());

        return parent::getNotificationSavs();
    }

    /**
     * {@inheritDoc}
     */
    public function setAmenagementEtude($amenagementEtude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmenagementEtude', array($amenagementEtude));

        return parent::setAmenagementEtude($amenagementEtude);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmenagementEtude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmenagementEtude', array());

        return parent::getAmenagementEtude();
    }

    /**
     * {@inheritDoc}
     */
    public function setTauxInvalidite($tauxInvalidite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTauxInvalidite', array($tauxInvalidite));

        return parent::setTauxInvalidite($tauxInvalidite);
    }

    /**
     * {@inheritDoc}
     */
    public function getTauxInvalidite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTauxInvalidite', array());

        return parent::getTauxInvalidite();
    }

    /**
     * {@inheritDoc}
     */
    public function setSuivi($suivi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuivi', array($suivi));

        return parent::setSuivi($suivi);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuivi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuivi', array());

        return parent::getSuivi();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateMaj($dateMaj)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateMaj', array($dateMaj));

        return parent::setDateMaj($dateMaj);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateMaj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateMaj', array());

        return parent::getDateMaj();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptifComplementaire($descriptifComplementaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptifComplementaire', array($descriptifComplementaire));

        return parent::setDescriptifComplementaire($descriptifComplementaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptifComplementaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptifComplementaire', array());

        return parent::getDescriptifComplementaire();
    }

}
